services:
  db:
    image: mysql:8.0.44@sha256:9c3380eac945af0736031b200027f581925927c81e010056214a4bd6b6693714
    restart: always
    environment:
      user: 1000:1000
    env_file: ".env.database"
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
  frontend:
    image: node:24-alpine@sha256:a1db41e58b58674705e9c5f886ab62fd906562087ee797632d3a30ed87219c4c
    container_name: nextjs-dev
    working_dir: /app
    # user: 1000:1000
    shm_size: 1g
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db
      - backend
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./web:/app
      - next_cache:/home/node/.cache
      - next_node_modules:/app/node_modules
      - next_next:/app/.next

  backend:
    image: ghcr.io/astral-sh/uv:python3.14-alpine
    user: 1000:1000
    working_dir: /app
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./backend:/app
    environment:
      UV_CACHE_DIR: /tmp/uv-cache
    command: /bin/sh -c "uv sync && uv run gunicorn -b 0.0.0.0:8000
      --reload --timeout 500 backend.wsgi:app"
    depends_on: [db]
    env_file: ".env.backend"

  nginx:
    image: nginx:alpine
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./web/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  uv_cache:
  python_env:
  data:
  next_cache:
  next_node_modules:
  next_next:
