services:
  db:
    image: mysql:8.0.44
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dogs
      MYSQL_DATABASE: cwa_db
      user: 1000:1000
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
  frontend:
    image: node:20-alpine
    container_name: nextjs-dev
    working_dir: /app
    # user: 1000:1000
    shm_size: 1g
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./web:/app
      - next_cache:/home/node/.cache
      - next_node_modules:/app/node_modules
      - next_next:/app/.next
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=dogs
      - MYSQL_DATABASE=cwa_db

  backend:
    image: python:3.12
    user: 1000:1000
    working_dir: /app
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./backend:/app
      - ./mysql/migrations:/app/mysql/migrations:ro
    command: /bin/bash -c "python -m venv venv && source venv/bin/activate && pip install -r requirements.txt &&  sleep 30 && venv/bin/python3 test/seed_user.py; gunicorn -b 0.0.0.0:8000 --reload main:app"
    depends_on: [db]
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8000
      - SEED_ADMIN_ID=admin
      - SEED_ADMIN_FIRST_NAME=Krista
      - SEED_ADMIN_LAST_NAME=Siehndel
      - SEED_ADMIN_EMAIL=cwawhippetracing@gmail.com
      - SEED_ADMIN_PASSWORD=dogs
      - SEED_ADMIN_ROLE=ADMIN
      - RESEND_API_KEY=REDACTED
      - FROM_EMAIL=onboarding@resend.dev
      - CONTACT_TO_EMAIL=##YOUR_CONTACT_EMAIL_HERE##
      - SITE_URL=http://localhost

  backup:
    image: mysql:8.0.44
    container_name: cwa-backup
    depends_on:
      - db
    volumes:
      - ./backups:/backups
      - ./backup.sh:/backup.sh
    entrypoint: >
      sh -c "
      chmod +x /backup.sh &&
      sleep 30 &&
      while true; do
        /backup.sh;
        sleep 86400;
      done"
  nginx:
    image: nginx:alpine
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  data:
  next_cache:
  next_node_modules:
  next_next:
